### ISSUE TITLE
Scrolling the feed causes app to wildly jump around and hitch

### ISSUE THREAD

**Issue by mt-xing** [micahlt/offsides#42]
**Describe the bug**
When scrolling down the main feed for long enough (usually after at least one load of additional posts), the feed will just randomly start jumping around. Scrolling beyond this point produces inconsistent behavior. Sometimes the screen will stop jumping and scroll correctly at a new seemingly random location. Sometimes the screen will jump back to where you were originally and scroll from there. Sometimes the feed just gets stuck in an infinite loop of jumping back and forth between a couple of random spots in the feed, rendering the app unusable.

**To Reproduce**
1. Open feed
2. Start scrolling
3. Keep scrolling until it breaks

**Screenshots**

Here's a relatively minor case I captured via screen recording:

https://github.com/user-attachments/assets/6f5c301d-2a18-4f10-a6e7-95563729e642

You can see the hitching, flashing, popping, and jumping as I scroll up through some posts.
Some of it happens because an image is loading on screen, but other times it seems entirely random.

Note that this is a high refresh rate video (~100 fps).

**Smartphone (please complete the following information):**
 - Device: Pixel Fold (using folded cover screen)
 - Android version: 15
 - App version 0.8.2 (also reproed on 0.8.1 and 0.8.0)

**Comment by micahlt** [comment]
You are correct - this is a known issue with the app.  To increase performance of the app when lots of posts are shown, posts are no longer rendered in the UI when they are not on screen (or close to being on screen).  This causes jumping around mostly due to images being unloaded and reloaded in the UI.  I'm considering several solutions to this, but thanks for the bug report!

**Comment by micahlt** [comment]
I've attempted to prevent extra re-renders - try to update and see if the issue is any better!

**Comment by agustinfitipaldi** [comment]
hello Micah, first off I'd like to say you're doing an incredible service with this app and I'm very happy to have found it. I got the most recent version, however, and this issue was something that I noticed as well and was able to replicate just now with version 0.8.4. After a bit of scrolling, the feed starts jumping around weirdly and behaving unpredictably. You can still keep scrolling, but it's a bit disorienting at times.

**Comment by micahlt** [comment]
Noted!  I will continue to do my best to solve this problem and enhance the app's performance.

**Comment by micahlt** [comment]
I believe I've fully fixed this issue in commit 3cdd09c4c72a770803c1eeed96057bf8dc002fb7 (aka the latest release, 0.8.8).  Can you check it out when you get a chance?

**Comment by micahlt** [comment]
I just released an update that should contribute a bit to solving this problem - download it and see if you notice any difference please!

**Comment by mt-xing** [comment]
I'm still seeing it happen from time to time on 0.8.8 but anecdotally it does seem to be better; I have to scroll a lot more before I see anything jump. I'm not at home at the moment but will try to get you a recording at some point, although the behavior looks the same as the previous recording, just less frequent.
